backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    description: "Collection of all news posts on the News page of the website."
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    description: "Collection of all pages on the website, includes: Home page, About page, Contact page, About page & News page. For modifying news posts please refer to the 'News' collection."
    delete: false
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Id", name: "id", widget: "hidden", default: "0"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Splash", name: "splash", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Subheading", name: "subheading", widget: "string"},
                {label: "Image (Desktop)", name: "largeimage", widget: "image"},
                {label: "Image (Mobile)", name: "smallimage", widget: "image"},
                {label: "Button", name: "button", widget: "object", fields: [
                    {label: "Name", name: "name", widget: "string"},
                    {label: "Url", name: "url", widget: "string"}
                ]}
            ]}
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Id", name: "id", widget: "hidden", default: "1"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: "People", name: "people", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Quote", name: "quote", widget: "text"},
              {label: "Image", name: "image", widget: "image"}
            ]}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Id", name: "id", widget: "hidden", default: "2"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: "Blurb", name: "blurb", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Body", name: "body", widget: "string"}
            ]}
          - {label: "Contacts", name: "contacts", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Position", name: "position", widget: "string"},
              {label: "Email", name: "email", widget: "string"}
            ]}
      - file: "content/news.md"
        label: "News Page"
        name: "news"
        fields:
          - {label: "Id", name: "id", widget: "hidden", default: "3"}
          - {label: "Title", name: "title", widget: "string"}
